[RHCLOUD-23693] Configurable default bundles
RedHatInsights/entitlements-api-go pull request #95
Opened 2023-01-18 04:10 UTC by Ellen-Yi-Dong

Make list of default bundles to be configurable so we don't need to change code with the new bundle. 

Added new parameter within deployment/deploy.yml and added it to the env. 

Updated config/main.go to reflect the changes made in deploy.yml

Related JIRA ticket: [RHCLOUD-23693](https://issues.redhat.com/browse/RHCLOUD-23693)
# Platform Security

## Secure Coding Practices Checklist Link
- https://github.com/RedHatInsights/secure-coding-checklist 

## Secure Coding Checklist
- [ ] Input Validation

- [ ] Output Encoding

- [ ] Authentication and Password Management

- [ ] Session Management

- [ ] Access Control

- [ ] Cryptographic Practices

- [ ] Error Handling and Logging

- [ ] Data Protection

- [ ] Communication Security

- [ ] System Configuration

- [ ] Database Security

- [ ] File Management

- [ ] Memory Management

- [ ] General Coding Practices

2023-01-24 20:31 UTC, lindgrenj6 reviewed
Just one tiny comment, otherwise looks good!

2023-01-24 20:31 UTC, lindgrenj6 commented on deployment/deploy.yml
> +  value: ansible, smart_management_rods, rhoam, rhosak, openshift, rhel
I think we just need to remove the spaces there - from what it was set to before I imagine it's splitting on the `","` character.

2023-01-31 13:56 UTC, lpichler commented
@Ellen-Yi-Dong can also create those envs for eph,stage, production - @ abaiken did similar thing here https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/56993

when we need to add bundle we just need to create MR with this change in app-interface.

2023-02-09 15:24 UTC, Ellen-Yi-Dong commented
I created the MR for the envs here: [](https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/58282)
Please let me know if anything should be added or changed! Thank you so much!!

2023-08-01 09:48 UTC, lpichler commented
@Ellen-Yi-Dong can you rebase please ? 🙏

2023-08-15 17:17 UTC, dagbay-rh requested changes
marking as needs work for now so I don't lose track of it in my todo list

lgtm tho pending the changes we talked about (getting clowdapp synced with deploy)

2023-08-23 16:24 UTC, dagbay-rh approved these changes
:cowboy_hat_face:

2023-08-24 11:18 UTC, merged